### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by hctilg** [language-ml/parsi.io#41]
In some Linux distributions, we encounter issues during setup while installing the 'camel-kenlm' module. This is due to the fact that its dependencies are not mentioned in the project and until they are installed, the installation of this module is not possible.

My solution was: 
```bash
sudo apt-get install gcc g++ libboost-all-dev zlib1g-dev libbz2-dev liblzma-dev
```

**Comment by SMesForoush** [comment]
Hi, 
Thank you for bringing this problem to our attention. I will add these dependencies to the documentation
